server:
  port: 8082
spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: mailtestcjh@gmail.com
    password: xohvhfpztqxdzaqo
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/SB_AM?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul&useOldAliasMetadataBehavior=true&zeroDateTimeNehavior=convertToNull
    username: root
    password: 
mybatis:
  type-aliases-package: com.koreaIT.demo.vo
custom:
  siteName: 2023_11_SB_AM
  siteMainUri: http://localhost:8082
  emailFrom: no-reply@localhost
  emailFromName: 2023_11_SB_AM
  
kakao:
  client:
    id: e9887fe498f68de5f200a52f1c4a9890
    secret: dsHwYcO83G3KuW7Bx6sNLUQg4kmnbKU9
  redirect:
    url: http://localhost:8082/kakao/callback